// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductClient is the client API for Product service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductClient interface {
	DeductStock(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error)
	DeductStockRollback(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error)
	CheckStock(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error)
}

type productClient struct {
	cc grpc.ClientConnInterface
}

func NewProductClient(cc grpc.ClientConnInterface) ProductClient {
	return &productClient{cc}
}

func (c *productClient) DeductStock(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error) {
	out := new(CheckStockResp)
	err := c.cc.Invoke(ctx, "/product.Product/deductStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) DeductStockRollback(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error) {
	out := new(CheckStockResp)
	err := c.cc.Invoke(ctx, "/product.Product/deductStockRollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) CheckStock(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error) {
	out := new(CheckStockResp)
	err := c.cc.Invoke(ctx, "/product.Product/checkStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServer is the server API for Product service.
// All implementations must embed UnimplementedProductServer
// for forward compatibility
type ProductServer interface {
	DeductStock(context.Context, *CheckStockReq) (*CheckStockResp, error)
	DeductStockRollback(context.Context, *CheckStockReq) (*CheckStockResp, error)
	CheckStock(context.Context, *CheckStockReq) (*CheckStockResp, error)
	mustEmbedUnimplementedProductServer()
}

// UnimplementedProductServer must be embedded to have forward compatible implementations.
type UnimplementedProductServer struct {
}

func (UnimplementedProductServer) DeductStock(context.Context, *CheckStockReq) (*CheckStockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductStock not implemented")
}
func (UnimplementedProductServer) DeductStockRollback(context.Context, *CheckStockReq) (*CheckStockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductStockRollback not implemented")
}
func (UnimplementedProductServer) CheckStock(context.Context, *CheckStockReq) (*CheckStockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStock not implemented")
}
func (UnimplementedProductServer) mustEmbedUnimplementedProductServer() {}

// UnsafeProductServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServer will
// result in compilation errors.
type UnsafeProductServer interface {
	mustEmbedUnimplementedProductServer()
}

func RegisterProductServer(s grpc.ServiceRegistrar, srv ProductServer) {
	s.RegisterService(&Product_ServiceDesc, srv)
}

func _Product_DeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).DeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.Product/deductStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).DeductStock(ctx, req.(*CheckStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_DeductStockRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).DeductStockRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.Product/deductStockRollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).DeductStockRollback(ctx, req.(*CheckStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_CheckStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).CheckStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.Product/checkStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).CheckStock(ctx, req.(*CheckStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Product_ServiceDesc is the grpc.ServiceDesc for Product service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Product_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.Product",
	HandlerType: (*ProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deductStock",
			Handler:    _Product_DeductStock_Handler,
		},
		{
			MethodName: "deductStockRollback",
			Handler:    _Product_DeductStockRollback_Handler,
		},
		{
			MethodName: "checkStock",
			Handler:    _Product_CheckStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
