Name: product.rpc
ListenOn: 127.0.0.1:8081
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
#mysql
DB:
  DataSource: root:iamchaichai@tcp(127.0.0.1:3306)/product?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai