// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-dtm/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/tcc/order/create",
				Handler: createTccOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/saga/order/create",
				Handler: createSagaOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/msg/order/create",
				Handler: createMsgOrderHandler(serverCtx),
			},
		},
	)
}
